### ISSUE TITLE
It can not use to ESP8266

### ISSUE THREAD

**Issue by be-engineer** [luoluomeng/NST1001Driver#1]
When I use it to ESP8266,I get compile error:

```
fatal error: driver/mcpwm.h: No such file or directory 
   10 | #include "driver/mcpwm.h"
```

What can I do for it?

**Comment by luoluomeng** [comment]
Unfortunately, there is nothing we can do for ESP8266.
As this implementation is based on mcpwm, it seems there is no mcpwm support for ESP8266.
